// Anime→manga adaptation resolver. Loads the per-series episode→chapter maps
// generated by server/scrapers/fandom.js (JSON under server/cache/maps/) and
// answers "the user watched episode N of anime X — what chapter do they read
// next?" for GET /api/manga/adaptation.
//
// Each franchise gets one file per anime with a flat `episodes` object keyed by
// episode number (Naruto restarts its numbering for Shippuden, so original and
// Shippuden live in separate files and are resolved via the registry below).

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const MAPS_DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'cache', 'maps')

// anilistId → cached map file. Add future franchises here (one-piece, bleach,
// jjk, demon-slayer, ...) once their wiki data is scraped into server/cache/maps/.
const SERIES = [
  { key: 'naruto', title: 'Naruto', anilistId: 20, file: 'naruto.json' },
  { key: 'naruto-shippuden', title: 'Naruto Shippuden', anilistId: 1735, file: 'naruto-shippuden.json' },
]

const loaded = new Map()

function loadMap(file) {
  if (!loaded.has(file)) {
    loaded.set(file, JSON.parse(fs.readFileSync(path.join(MAPS_DIR, file), 'utf8')))
  }
  return loaded.get(file)
}

export function resetAdaptationCache() {
  loaded.clear()
}

export function isKnownAnime(animeId) {
  return SERIES.some((s) => s.anilistId === Number(animeId))
}

function previousCanonEpisode(episodes, episode) {
  for (let n = episode - 1; n >= 1; n--) {
    const e = episodes[String(n)]
    if (e && !e.filler) return n
  }
  return null
}

// Resolve the next chapter to read after `episode` of `animeId`.
// Returns { result } on success or { notFound: 'unknown-anime'|'unknown-episode' }.
export function getAdaptation(animeId, episode) {
  const series = SERIES.find((s) => s.anilistId === Number(animeId))
  if (!series) return { notFound: 'unknown-anime' }

  const data = loadMap(series.file)
  const epNum = Number(episode)
  if (!Number.isInteger(epNum) || epNum < 1) return { notFound: 'unknown-episode' }
  const entry = data.episodes[String(epNum)]
  if (!entry) return { notFound: 'unknown-episode' }

  const result = {
    animeId: series.anilistId,
    series: series.key,
    animeTitle: series.title,
    episode: epNum,
    lastAdaptedChapter: entry.filler ? null : entry.lastChapter,
    nextChapter: entry.nextChapter,
    filler: entry.filler,
  }
  if (entry.filler) {
    result.previousCanonEpisode = previousCanonEpisode(data.episodes, epNum)
  }
  return { result }
}
